# Generated by Django 3.1.7 on 2021-02-27 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Режисер',
                'verbose_name_plural': 'Режисеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('actors', models.CharField(max_length=150, verbose_name='Актеры')),
                ('comment', models.TextField(blank=True, max_length=150, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('counter', models.IntegerField(default=0, verbose_name='Число просмотров')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер')),
                ('is_watched', models.BooleanField(default=True)),
                ('mark', models.IntegerField(verbose_name='Оценка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='films', to='fseen.category')),
                ('director', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='films', to='fseen.director')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['title'],
            },
        ),
    ]
