# Generated by Django 3.1.7 on 2021-02-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fseen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='films', to='fseen.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='films', to='fseen.director', verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='is_watched',
            field=models.BooleanField(default=True, verbose_name='Просмотренно'),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Постер'),
        ),
    ]
