# Generated by Django 3.1.7 on 2021-03-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fseen', '0002_auto_20210228_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.CharField(default='-', max_length=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='mark',
            field=models.IntegerField(verbose_name='Моя оценка'),
        ),
    ]
