# Generated by Django 3.1.7 on 2021-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fseen', '0003_auto_20210306_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='mark',
            field=models.IntegerField(blank=True, verbose_name='Моя оценка'),
        ),
    ]
