# Generated by Django 3.1.7 on 2021-03-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fseen', '0004_auto_20210306_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='mark',
            field=models.IntegerField(blank=True, null=True, verbose_name='Моя оценка'),
        ),
    ]
