# Generated by Django 3.1.7 on 2021-03-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fseen', '0005_auto_20210306_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default=2, max_length=50, verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
