# Generated by Django 3.1.7 on 2021-03-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fseen', '0007_auto_20210307_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name'], 'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры'},
        ),
    ]
