# Generated by Django 3.1.7 on 2021-03-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fseen', '0008_auto_20210307_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
